name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version:
          - 1.25.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check format
        run: deno fmt --check

      - name: Lint source files
        run: deno lint

      - name: Run tests
        run: deno test --allow-net
